### ISSUE TITLE
Ideas from gistio/issues

### ISSUE THREAD

**Issue by x3ro** [x3ro/draft.sx#3]
Evaluate these nice ideas, mostly by @whit537
- [ ] Implement kudos (idan/gistio#46)
- [x] put title in `<title>` (idan/gistio#43)
- [ ] Add HTML anchors to headlines (idan/gistio#37)
- [ ] Show number of views? (idan/gistio#30)
- [ ] Show author avatar if the gist isn't anonymous

**Comment by datenreisender** [comment]
I am really missing HTML anchors for the headlines. 🙁
